=== Midra429/nco-utils/schema/parse-examples.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "input": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "titleStripped": {
        "type": "string"
      },
      "season": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "number": {
            "type": "number"
          }
        }
      },
      "seasonAlt": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "number": {
            "type": "number"
          }
        }
      },
      "episode": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "number": {
            "type": "number"
          }
        }
      },
      "episodeAlt": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "number": {
            "type": "number"
          }
        }
      },
      "episodes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "number": {
              "type": "number"
            }
          }
        }
      },
      "episodesDivider": {
        "type": "string"
      },
      "subtitle": {
        "type": "string"
      },
      "subtitleStripped": {
        "type": "string"
      }
    }
  }
}

=== Midra429/nco-utils/test/parse-examples.json
[
  {
    "id": 1,
    "input": "ダンジョン飯　第１９話　「山姥／夢魔」",
    "title": "ダンジョン飯",
    "episode": {
      "text": "第19話",
      "number": 19
    },
    "subtitle": "山姥/夢魔"
  },

  {
    "id": 2,
    "input": "姫様“拷問”の時間です 第1話 姫様“拷問”の時間です",
    "title": "姫様“拷問”の時間です",
    "episode": {
      "text": "第1話",
      "number": 1
    },
    "subtitle": "姫様“拷問”の時間です"
  },

  {
    "id": 3,
    "input": "キミと僕の最後の戦場、あるいは世界が始まる聖戦 Season Ⅱ 第12話「暁星 ―拍手と喝采で出迎えよ―」",
    "title": "キミと僕の最後の戦場、あるいは世界が始まる聖戦",
    "season": {
      "text": "Season II",
      "number": 2
    },
    "episode": {
      "text": "第12話",
      "number": 12
    },
    "subtitle": "暁星 -拍手と喝采で出迎えよ-"
  },

  {
    "id": 4,
    "input": "ウィッチウォッチ 第14話 うろんミラージュ　第１１９話「ファジー討伐-４」/推し絵師日誌",
    "title": "ウィッチウォッチ",
    "episode": {
      "text": "第14話",
      "number": 14
    },
    "subtitle": "うろんミラージュ 第119話「ファジー討伐-4」/推し絵師日誌"
  },

  {
    "id": 5,
    "input": "転生したらスライムだった件 第3期 第65.5話 閑話：ルミナスメモリーズ",
    "title": "転生したらスライムだった件",
    "season": {
      "text": "第3期",
      "number": 3
    },
    "episode": {
      "text": "第65.5話",
      "number": 65.5
    },
    "subtitle": "閑話:ルミナスメモリーズ"
  },

  {
    "id": 6,
    "input": "まちカドまぞく 2丁目 第1話 対決ふたたび！　魔法少女の新たなる姿！？",
    "title": "まちカドまぞく",
    "season": {
      "text": "2丁目",
      "number": 2
    },
    "episode": {
      "text": "第1話",
      "number": 1
    },
    "subtitle": "対決ふたたび! 魔法少女の新たなる姿!?"
  },

  {
    "id": 7,
    "input": "わたしが恋人になれるわけないじゃん、ムリムリ!（※ムリじゃなかった!?）　5話　恋人とか、ぜったいにムリ!その２",
    "title": "わたしが恋人になれるわけないじゃん、ムリムリ!(※ムリじゃなかった!?)",
    "episode": {
      "text": "5話",
      "number": 5
    },
    "subtitle": "恋人とか、ぜったいにムリ!その2"
  },

  {
    "id": 8,
    "input": "タコピーの原罪 第5話「2022年のきみへ」",
    "title": "タコピーの原罪",
    "episode": {
      "text": "第5話",
      "number": 5
    },
    "subtitle": "2022年のきみへ"
  },

  {
    "id": 9,
    "input": "DEVIL SURVIVOR 2 the ANIMATION　第1話「1ST DAY 憂鬱の日曜日」",
    "title": "DEVIL SURVIVOR 2 the ANIMATION",
    "episode": {
      "text": "第1話",
      "number": 1
    },
    "subtitle": "1ST DAY 憂鬱の日曜日"
  },

  {
    "id": 10,
    "input": "Dr.STONE SCIENCE FUTURE（第4期）　第16話　MEDUSA MECHANISM",
    "title": "Dr.STONE SCIENCE FUTURE",
    "season": {
      "text": "第4期",
      "number": 4
    },
    "episode": {
      "text": "第16話",
      "number": 16
    },
    "subtitle": "MEDUSA MECHANISM"
  },

  {
    "id": 11,
    "input": "ひみつのアイプリ リング編 第13話 (64話) 「マイメロディとクロミがやってきた」",
    "title": "ひみつのアイプリ リング編",
    "episode": {
      "text": "第13話",
      "number": 13
    },
    "episodeAlt": {
      "text": "64話",
      "number": 64
    },
    "subtitle": "マイメロディとクロミがやってきた"
  },

  {
    "id": 12,
    "input": "彼女、お借りします Season4 第5話（41話）「「その時と彼女」 ―バッカノ―」",
    "title": "彼女、お借りします",
    "season": {
      "text": "Season4",
      "number": 4
    },
    "episode": {
      "text": "第5話",
      "number": 5
    },
    "episodeAlt": {
      "text": "41話",
      "number": 41
    },
    "subtitle": "「その時と彼女」 -バッカノ-"
  },

  {
    "id": 13,
    "input": "テレビアニメ「鬼滅の刃」竈門炭治郎 立志編 　第一話　残酷",
    "title": "鬼滅の刃 竈門炭治郎 立志編",
    "episode": {
      "text": "第一話",
      "number": 1
    },
    "subtitle": "残酷"
  },

  {
    "id": 15,
    "input": "シュタインズ・ゲート 第1話「始まりと終わりのプロローグ -Turning Point- 」",
    "title": "シュタインズ・ゲート",
    "episode": {
      "text": "第1話",
      "number": 1
    },
    "subtitle": "始まりと終わりのプロローグ -Turning Point-"
  },

  {
    "id": 16,
    "input": "STEINS;GATE　第1話　始まりと終わりのプロローグ",
    "title": "STEINS;GATE",
    "episode": {
      "text": "第1話",
      "number": 1
    },
    "subtitle": "始まりと終わりのプロローグ"
  },

  {
    "id": 17,
    "input": "杖と剣のウィストリア 第ニ話 不屈のごとく",
    "title": "杖と剣のウィストリア",
    "episode": {
      "text": "第ニ話",
      "number": 2
    },
    "subtitle": "不屈のごとく"
  },

  {
    "id": 18,
    "input": "機動戦士Gundam GQuuuuuuX（ジークアクス） 1話 赤いガンダム",
    "title": "機動戦士Gundam GQuuuuuuX(ジークアクス)",
    "episode": {
      "text": "1話",
      "number": 1
    },
    "subtitle": "赤いガンダム"
  },

  {
    "id": 19,
    "input": "陰の実力者になりたくて！ 2nd season(第2期) #01 無法都市",
    "title": "陰の実力者になりたくて!",
    "season": {
      "text": "2nd season",
      "number": 2
    },
    "seasonAlt": {
      "text": "第2期",
      "number": 2
    },
    "episode": {
      "text": "#01",
      "number": 1
    },
    "subtitle": "無法都市"
  },

  {
    "id": 20,
    "input": "ポプテピピック TVアニメーション作品第二シリーズ　#3　POPUTAN",
    "title": "ポプテピピック",
    "season": {
      "text": "第二シリーズ",
      "number": 2
    },
    "episode": {
      "text": "#3",
      "number": 3
    },
    "subtitle": "POPUTAN"
  },

  {
    "id": 21,
    "input": "フードコートで、また明日。 ＃4『キャラメルリボン』『別方向だけど』『臭くはない』『一般的和田』",
    "title": "フードコートで、また明日。",
    "episode": {
      "text": "#4",
      "number": 4
    },
    "subtitle": "『キャラメルリボン』『別方向だけど』『臭くはない』『一般的和田』"
  },

  {
    "id": 22,
    "input": "「その着せ替え人形（ビスク・ドール）は恋をする」Season 2 #15「日常パートめっちゃすこ〰〰〰〰♡♡♡」",
    "title": "その着せ替え人形(ビスク・ドール)は恋をする",
    "season": {
      "text": "Season 2",
      "number": 2
    },
    "episode": {
      "text": "#15",
      "number": 15
    },
    "subtitle": "日常パートめっちゃすこ〜〜〜〜♡♡♡"
  },

  {
    "id": 23,
    "input": "「その着せ替え人形は恋をする」Season 2　#15　日常パートめっちゃすこ〰〰〰〰♡♡♡",
    "title": "その着せ替え人形は恋をする",
    "season": {
      "text": "Season 2",
      "number": 2
    },
    "episode": {
      "text": "#15",
      "number": 15
    },
    "subtitle": "日常パートめっちゃすこ〜〜〜〜♡♡♡"
  },

  {
    "id": 24,
    "input": "Lv2からチートだった元勇者候補のまったり異世界ライフ　episode.6　光と闇の魔人ヒヤ",
    "title": "Lv2からチートだった元勇者候補のまったり異世界ライフ",
    "episode": {
      "text": "episode.6",
      "number": 6
    },
    "subtitle": "光と闇の魔人ヒヤ"
  },

  {
    "id": 25,
    "input": "ツンデレ悪役令嬢リーゼロッテと実況の遠藤くんと解説の小林さん chapter 1 ツンデレと王子と天の声",
    "title": "ツンデレ悪役令嬢リーゼロッテと実況の遠藤くんと解説の小林さん",
    "episode": {
      "text": "chapter 1",
      "number": 1
    },
    "subtitle": "ツンデレと王子と天の声"
  },

  {
    "id": 26,
    "input": "中二病でも恋がしたい!　第11話「片翼の･･･堕天使（フォーリン・エンジェル）」",
    "title": "中二病でも恋がしたい!",
    "episode": {
      "text": "第11話",
      "number": 11
    },
    "subtitle": "片翼の・・・堕天使(フォーリン・エンジェル)"
  },

  {
    "id": 27,
    "input": "中二病でも恋がしたい！　Episode XI　片翼の堕天使(フォーリン・エンジェル)",
    "title": "中二病でも恋がしたい!",
    "episode": {
      "text": "Episode XI",
      "number": 11
    },
    "subtitle": "片翼の堕天使(フォーリン・エンジェル)"
  },

  {
    "id": 28,
    "input": "魔法科高校の劣等生 第3シーズン 01「ダブル・セブン編Ⅰ」",
    "title": "魔法科高校の劣等生",
    "season": {
      "text": "第3シーズン",
      "number": 3
    },
    "episode": {
      "text": "01",
      "number": 1
    },
    "subtitle": "ダブル・セブン編I"
  },

  {
    "id": 29,
    "input": "魔法科高校の劣等生 3期 01 ダブル・セブン編Ⅰ",
    "title": "魔法科高校の劣等生",
    "season": {
      "text": "3期",
      "number": 3
    },
    "subtitle": "ダブル・セブン編I"
  },

  {
    "id": 30,
    "input": "シャングリラ・フロンティア 2nd Season 27「融通知らずの門番」",
    "title": "シャングリラ・フロンティア",
    "season": {
      "text": "2nd Season",
      "number": 2
    },
    "episode": {
      "text": "27",
      "number": 27
    },
    "subtitle": "融通知らずの門番"
  },

  {
    "id": 31,
    "input": "イジらないで、長瀞さん 2nd Attack 1 センパイと私の仲なんスから～",
    "title": "イジらないで、長瀞さん",
    "season": {
      "text": "2nd Attack",
      "number": 2
    },
    "episode": {
      "text": "1",
      "number": 1
    },
    "subtitle": "センパイと私の仲なんスから〜"
  },

  {
    "id": 32,
    "input": "炎炎ノ消防隊 壱ノ章 第参話 消防官新人大会",
    "title": "炎炎ノ消防隊",
    "season": {
      "text": "壱ノ章",
      "number": 1
    },
    "episode": {
      "text": "第参話",
      "number": 3
    },
    "subtitle": "消防官新人大会"
  },

  {
    "id": 33,
    "input": "炎炎ノ消防隊 弐ノ章 第伍話 \"悪魔の型\"/秘策",
    "title": "炎炎ノ消防隊",
    "season": {
      "text": "弐ノ章",
      "number": 2
    },
    "episode": {
      "text": "第伍話",
      "number": 5
    },
    "subtitle": "\"悪魔の型\"/秘策"
  },

  {
    "id": 34,
    "input": "美男高校地球防衛部ハイカラ！ 第肆話「お母さんって　ハイカラだぜ！」",
    "title": "美男高校地球防衛部ハイカラ!",
    "episode": {
      "text": "第肆話",
      "number": 4
    },
    "subtitle": "お母さんって ハイカラだぜ!"
  },

  {
    "id": 35,
    "input": "ご注文はうさぎですか？？ 第1羽 笑顔とフラッシュがやかましい　これが私の自称姉です",
    "title": "ご注文はうさぎですか??",
    "episode": {
      "text": "第1羽",
      "number": 1
    },
    "subtitle": "笑顔とフラッシュがやかましい これが私の自称姉です"
  },

  {
    "id": 36,
    "input": "月が導く異世界道中　第二幕　第一夜　え？荒城の月？",
    "title": "月が導く異世界道中",
    "season": {
      "text": "第二幕",
      "number": 2
    },
    "episode": {
      "text": "第一夜",
      "number": 1
    },
    "subtitle": "え?荒城の月?"
  },

  {
    "id": 37,
    "input": "本好きの下剋上 司書になるためには手段を選んでいられません　第九章『ギルド長の孫娘』",
    "title": "本好きの下剋上 司書になるためには手段を選んでいられません",
    "episode": {
      "text": "第九章",
      "number": 9
    },
    "subtitle": "ギルド長の孫娘"
  },

  {
    "id": 38,
    "input": "クレバテス-魔獣の王と赤子と屍の勇者-　第6幕　虫を操る魔道士",
    "title": "クレバテス-魔獣の王と赤子と屍の勇者-",
    "episode": {
      "text": "第6幕",
      "number": 6
    },
    "subtitle": "虫を操る魔道士"
  },

  {
    "id": 39,
    "input": "響け!ユーフォニアム3 第一回 あらたなユーフォニアム",
    "title": "響け!ユーフォニアム",
    "season": {
      "text": "3",
      "number": 3
    },
    "episode": {
      "text": "第一回",
      "number": 1
    },
    "subtitle": "あらたなユーフォニアム"
  },

  {
    "id": 40,
    "input": "地縛少年花子くん２ 第17の怪「アオイとアカネ」",
    "title": "地縛少年花子くん",
    "season": {
      "text": "2",
      "number": 2
    },
    "episode": {
      "text": "第17の怪",
      "number": 17
    },
    "subtitle": "アオイとアカネ"
  },

  {
    "id": 41,
    "input": "カッコウの許嫁Season2 4羽目「みなさんおそろいで」",
    "title": "カッコウの許嫁",
    "season": {
      "text": "Season2",
      "number": 2
    },
    "episode": {
      "text": "4羽目",
      "number": 4
    },
    "subtitle": "みなさんおそろいで"
  },

  {
    "id": 42,
    "input": "Turkey!　5投目　すれ違って、フックボール",
    "title": "Turkey!",
    "episode": {
      "text": "5投目",
      "number": 5
    },
    "subtitle": "すれ違って、フックボール"
  },

  {
    "id": 43,
    "input": "名湯『異世界の湯』開拓記 ～アラフォー温泉マニアの転生先は、のんびり温泉天国でした～ 1番湯 狐少女と温泉の作法",
    "title": "名湯『異世界の湯』開拓記 〜アラフォー温泉マニアの転生先は、のんびり温泉天国でした〜",
    "episode": {
      "text": "1番湯",
      "number": 1
    },
    "subtitle": "狐少女と温泉の作法"
  },

  {
